server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/food_order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Config
# We disable Flyway here so that ONLY order-service runs the DB migrations
spring.flyway.enabled=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
